import Head from 'next/head'
import { useQuery } from 'urql'
import {PRODUCT_QUERY} from '../lib/query'
import Products from '../components/Products'
import { Gallery } from '../styles/Gallery'
import {AiFillTwitterCircle, AiFillGithub, AiFillLinkedin} from 'react-icons/ai'
import { useEffect, useState } from 'react'
import Slider from '@mui/material/Slider';
import productStyle from '../pages/products/product.module.css'
import  prodData from '../lib/data.json'

export default function SS() {

  const [results] = useQuery({query: PRODUCT_QUERY})
  const {data, fetching, error} = results
  const [filteredProducts, setFilteredProducts] = useState([])
  const [newfilteredProducts, setNewFilteredProducts] = useState([])
  const [priceFilter, setPriceFilter] = useState()
  const [checkboxFilter, setCheckboxFilter] = useState([])

  useEffect(() => {
    setFilteredProducts(JSON.parse(localStorage.getItem('prods')))
    setNewFilteredProducts(JSON.parse(localStorage.getItem('prods')))
  }, [])

  
  const products = prodData.products.data

function sliderData(e) {
  setPriceFilter(e.target.value)
  filterbyPrice()
}

function filterbyPrice() {
  if (checkboxFilter.includes('Jordan')) {
    setNewFilteredProducts(filteredProducts.filter(prod => prod.attributes.price < priceFilter && prod.attributes.title.includes('Jordan')))
  } else if (checkboxFilter.includes('Air')) {
    setNewFilteredProducts(filteredProducts.filter(prod => prod.attributes.price < priceFilter && prod.attributes.title.includes('Air')))
} else if (checkboxFilter.includes('Air') && checkboxFilter.includes('Jordan') ) {
  setNewFilteredProducts(filteredProducts.filter(prod => prod.attributes.price < priceFilter && prod.attributes.title.includes('Air') && prod.attributes.title.includes('Jordan')))
} else {
  setNewFilteredProducts(filteredProducts.filter(prod => prod.attributes.price < priceFilter))
} 

}

function handleCheckbox(e) {
  if (checkboxFilter.includes(e.target.value)) {
    setCheckboxFilter(prevState => prevState.filter(value => value !== e.target.value))
  } else {
   setCheckboxFilter(prevState => [...prevState, e.target.value])
}
}

function domProds() {
  if (checkboxFilter.length > 1) {
    return newfilteredProducts.map(product => 
      <Products {...product} key={product.attributes.slug}/>
      )
  } else if (checkboxFilter.includes('Air')) {
    return newfilteredProducts.filter(prod => prod.attributes.title.includes('Air')).map(product => 
      <Products {...product} key={product.attributes.slug}/>
      )
  }
  else if (checkboxFilter.includes('Jordan')) {
    return newfilteredProducts.filter(prod => prod.attributes.title.includes('Jordan')).map(product => 
      <Products {...product} key={product.attributes.slug}/>
      )
  } else {
    return newfilteredProducts.map(product => 
      <Products {...product} key={product.attributes.slug}/>
      )
  }
}

  return (
    <div>
      <Head>
        <title>COZY X NIKE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='filters'>
          <div className='slider'>
            <p>Filter by price</p>
          <Slider
        defaultValue={300}
        aria-label="Small"
        valueLabelDisplay="auto"
        min={129}
        onChange={e => sliderData(e)}
  max={300}
      />
          </div>
          <div className='checkbox'>
          <p>Filter by type</p>
          <label><input type="checkbox" name="Air" value='Air' onClick={e => handleCheckbox(e)}/>Nike Air</label>
          <label><input type="checkbox" name="Air" value='Jordan' onClick={e => handleCheckbox(e)}/>Jordan</label>
          </div>
        </div>
        <Gallery>
        {domProds()}
        </Gallery>
      </main>
      <footer>
            <div className='col-one'>
              <p>Find us</p>
              <p>Gift Cards</p>
              <p>Send Us Feedback</p>
              <p>Sign Up For Email</p>
            </div>
            <div className='col-two'>
            <p>Get Help</p>
            <p>Contact Us</p>
            <p>Chat With Us</p>
            </div>

            <div className='col-three'>
            <AiFillTwitterCircle style={{ margin: '0rem 0.5rem' }} size={25}/>
            <AiFillGithub style={{ margin: '0rem 0.5rem' }}  size={25}/>
            <AiFillLinkedin style={{ margin: '0rem 0.5rem' }}  size={25}/>
            </div>
          </footer>
    </div>
  )
}
